export const produtos = {
  Items: [
    { id: 1, nome: "Bola", cor: "verde", tamanho: "Único", categoria: "Esporte" },
    { id: 2, nome: "bola de basquete", cor: "vermelho", tamanho: "Grande", categoria: "Esporte" },
    { id: 3, nome: "capacete", cor: "azul", tamanho: "Médio", categoria: "Esporte" },
    { id: 4, nome: "Camiseta", cor: "preto", tamanho: "G", categoria: "Vestuário" },
    { id: 5, nome: "Tênis", cor: "branco", tamanho: "41", categoria: "Vestuário" },
    { id: 6, nome: "Sapato", cor: "preto", tamanho: "38", categoria: "Vestuário" },
    { id: 7, nome: "bicicleta", cor: "verde", tamanho: "Único", categoria: "Esporte" },
    { id: 8, nome: "moto", cor: "vermelho", tamanho: "Grande", categoria: "Esporte" },
    { id: 9, nome: "carro", cor: "azul", tamanho: "Médio", categoria: "Esporte" },
    { id: 10, nome: "Camiseta", cor: "preto", tamanho: "G", categoria: "Vestuário" },
    { id: 11, nome: "blusa de frio", cor: "branco", tamanho: "41", categoria: "Vestuário" },
    { id: 12, nome: "jaleco", cor: "preto", tamanho: "38", categoria: "Vestuário" },
    { id: 13, nome: "meia", cor: "verde", tamanho: "Único", categoria: "Esporte" },
    { id: 14, nome: "touca", cor: "vermelho", tamanho: "Grande", categoria: "Esporte" },
    { id: 15, nome: "capacete", cor: "azul", tamanho: "Médio", categoria: "Esporte" },
    { id: 16, nome: "Camiseta", cor: "preto", tamanho: "G", categoria: "Vestuário" },
    { id: 17, nome: "Tênis", cor: "branco", tamanho: "41", categoria: "Vestuário" },
    { id: 18, nome: "Sapato", cor: "preto", tamanho: "38", categoria: "Vestuário" },
    { id: 19, nome: "Bola", cor: "violeta", tamanho: "Único", categoria: "Esporte" },
    { id: 20, nome: "bola de basquete", cor: "vermelho", tamanho: "Grande", categoria: "Esporte" },
    { id: 21, nome: "capacete", cor: "azul", tamanho: "Médio", categoria: "Esporte" },
    { id: 22, nome: "Camiseta", cor: "preto", tamanho: "G", categoria: "Vestuário" },
    { id: 23, nome: "Tênis", cor: "branco", tamanho: "41", categoria: "Vestuário" },
    { id: 24, nome: "Sapato", cor: "preto", tamanho: "38", categoria: "Vestuário" },
    { id: 25, nome: "Bola", cor: "ciano", tamanho: "Único", categoria: "Esporte" },
    { id: 26, nome: "bola de basquete", cor: "vermelho", tamanho: "Grande", categoria: "Esporte" },
    { id: 27, nome: "capacete", cor: "azul", tamanho: "Médio", categoria: "Esporte" },
    { id: 28, nome: "Camiseta", cor: "preto", tamanho: "G", categoria: "Vestuário" },
    { id: 29, nome: "Tênis", cor: "branco", tamanho: "41", categoria: "Vestuário" },
    { id: 30, nome: "Sapato", cor: "preto", tamanho: "38", categoria: "Vestuário" },
    { id: 31, nome: "Bola", cor: "verde", tamanho: "Único", categoria: "Esporte" },
    { id: 32, nome: "bola de basquete", cor: "vermelho", tamanho: "Grande", categoria: "Esporte" },
    { id: 33, nome: "capacete", cor: "azul", tamanho: "Médio", categoria: "Esporte" },
    { id: 34, nome: "Camiseta", cor: "preto", tamanho: "G", categoria: "Vestuário" },
    { id: 35, nome: "Tênis", cor: "branco", tamanho: "41", categoria: "Vestuário" },
  ],
};
